version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
    networks:
      - app

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8000:8080
    networks:
      - app
    depends_on: 
      - mysql

  node:
    build: ./node
    container_name: node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s node index.js
    networks: 
      - app
  
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - app
    depends_on: 
      - mysql

networks:
  app:
    driver: bridge